---

- name: update apt cache
  raw: apt-get --version &> /dev/null && apt-get update || true

- name: install python via apt-get when not found in PATH
  raw: (python --version &> /dev/null && apt-get --version &> /dev/null) || apt-get -y install python python-apt || true

- name: install python via dnf
  raw: (python --version &> /dev/null && dnf --version &> /dev/null) || dnf install -y python2 python2-dnf libselinux-python || true

- setup:
